### ISSUE TITLE
Build Kernel Script Fails because branch was already checked out

### ISSUE THREAD

**Issue by PhilippvK** [Groboards/giantboard-tools#11]
I am building the Giantboard Kernel using the scripts in this repository on a Ubuntu 18.04 VM.

However in my setup the line 36 of the script `scripts/build_kernel.sh` does not work in my setup, so I commented it out:

```
# always do a checkout to see if chosen kernel version has changed
git -C ${linux_dir} checkout ${release} -b tmp
```

I am (obviously) getting the error message: fatal: `Branch 'tmp' already exists.`

I am not exactly sure if this is caused by my version of git but maybe it would be great (for other users) to replace this line with a statement which works everywhere.

I hope my explanation was understandable.

**Comment by Groguard** [comment]
You likely already have a local git branch named tmp from another project. You'll need to delete that before you can build this. You can also change the name from tmp to something else.
