### ISSUE TITLE
Docs are gone

### ISSUE THREAD

**Issue by scott8** [Groboards/giantboard-tools#14]
Hi!
Where are the docs that used to be here?
https://groboards.com/docs/custom-giant-board-images/

Thanks!
Scott

**Comment by Groguard** [comment]
Hello, the docs have been moved to this repo https://github.com/Groboards/GiantBoardDocs/wiki. Sorry for the confusion.

**Comment by scott8** [comment]
The link on this page needs to be updated:
https://github.com/Groboards/giantboard-tools/

**Comment by Groguard** [comment]
Should be updated now. Thanks
