### ISSUE TITLE
GiantBoard power management

### ISSUE THREAD

**Issue by h-milz** [Groboards/giantboard-tools#15]
Hi, I'm using a GB v0.9.2 on a Keyboard featherwing v2 and I'm trying to get power management to work. I studied the schematics, the related kernel source code and the datasheets for the MCU (including the relevant Atmel application notes) and the PMIC thoroughly. The images I tried were the default Debian 9 based images for blackberry and the standard image, as well as a Debian 11 based image with a custom built kernel 5.4.0 made with the giantboard-tools. The following description happens in all 3 environments. 

Apparently, powering up / down as documented seems not to work, i.e. using the PB1 button or the KBFW slide switch.  

What happens: 
- during run mode, click button. Expected: board should power down. But nothing happens. 
- sending board to standby using "echo standby > /sys/power/state" appears to send board to standby - at least the current consumption goes down by about 40mA. Clicking button does not wake up the board. 
- sending board to suspend-to-RAM using "echo mem > /sys/power/state" does nothing. The board is not sent to ULP1 as directed in uEnv.txt. But the board reboots after a moment and comes back up. The current consumption is unchanged, and in particular the VDD_3V3 line is not disabled, leaving the KBFW in its on state and consuming power. I'd expect VDD_3V3 to be disabled as configured in at91-sama5d27_giantboard.dts. 
- changing atmel.pm-modes to "standby,backup" and calling "echo mem > /sys/power/state"  should send the board to BSR according to the atmel documentation and the kernel code, but this does not happen. The board does power down in a way but VDD_3V3 again stays active, and the whole system still consumes 137 mA. Clicking button does not wake up the board. 

What gives? Am I looking for a software or hardware issue? Do I explictly need to set a wakeup mechanism? I mean the PMIC works in a pretty straightforward way: click button and assert nPBIN, PMIC asserts nPBSTAT and thus WKUP, and the MCU BU domain should wake up and assert SHDN. But this does not seem to work somehow. 

The only workaround would be to cut the red battery wire and insert another slide switch (plus a I2C RTC because I want to have a real time clock), but this cannot be right ... 

Thank you! 

PS Is there any more direct way to contact you concerning the board than a GitHub issue or using Twitter / X (which I do not want to have), eg e-mail? 

PPS: other than the described issue, the system works fine using Python3 w/ mpmath, numpy, matplotlib, uncertainties and fractions, and sympy (albeit slow), as well as giac and octave-cli. Nice and powerful scientific pocket calculator. :-) Using busybox init and a fast SD card (sync mounted), I got the boot time down to 8 seconds so that having to do a full boot each time won't hurt too much.

**Comment by Groguard** [comment]
Hello, this project has been dead for several years and I'm just replying as a courtesy.

-  The button will never shut the device down, it doesn't have the functionality. You would need to setup your own shutdown button in the overlay.

- If I remember correctly you would need to solder a jumper wire to gain access to the interrupt, which would allow the button to wake the giant board. I didn't design the keyboard featherwing so unfortunately its not supported entirely. I've attached a photo below for the jumper to solder.

- As far as the issues with sleeping go, they should work as described in the atmel documentation. I'm not entirely sure why they wouldn't work as described. When I tested all the software a long time ago everything was working as described.

![solderint](https://github.com/Groboards/giantboard-tools/assets/16845266/3fea88bb-3516-4410-8fe1-a5850efdc652)
